// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFCKSmd5XzAy6wzbuf3ZXv-ctzHUtMgA',
    appId: '1:175121945503:android:9104650d9a466e820663aa',
    messagingSenderId: '175121945503',
    projectId: 'dghome3d-11a73',
    storageBucket: 'dghome3d-11a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGi-9oGJwEbF7B_TUieg5Dyh0VEiLJdMY',
    appId: '1:175121945503:ios:cb3b3e330217a3810663aa',
    messagingSenderId: '175121945503',
    projectId: 'dghome3d-11a73',
    storageBucket: 'dghome3d-11a73.appspot.com',
    iosClientId: '175121945503-foqhf0dh0s8k8gd41vb7gkah9fkfo5ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.dghome3d',
  );
}
